package tg.bot.rssgo.util;

import java.util.HashMap;


public class EmojiUtil {

    public static HashMap<String, String> emojiMap = new HashMap<>();
    static{
        emojiMap.put("微笑", "🙂");
        emojiMap.put("可爱", "😊");
        emojiMap.put("太开心", "😆");
        emojiMap.put("鼓掌", "👏");
        emojiMap.put("嘻嘻", "😁");
        emojiMap.put("哈哈", "😄");
        emojiMap.put("笑cry", "😂");
        emojiMap.put("挤眼", "😜");
        emojiMap.put("馋嘴", "😋");
        emojiMap.put("黑线", "😑");
        emojiMap.put("汗", "😓");
        emojiMap.put("哼", "😠");
        emojiMap.put("怒", "😡");
        emojiMap.put("可怜", "🥺");
        emojiMap.put("失望", "😞");
        emojiMap.put("悲伤", "😢");
        emojiMap.put("泪", "😭");
        emojiMap.put("害羞", "😳");
        emojiMap.put("爱你", "🥰");
        emojiMap.put("亲亲", "😚");
        emojiMap.put("色", "😍");
        emojiMap.put("阴险", "😏");
        emojiMap.put("偷笑", "🤭");
        emojiMap.put("酷", "😎");
        emojiMap.put("并不简单", "🧐");
        emojiMap.put("思考", "🤔");
        emojiMap.put("晕", "😵");
        emojiMap.put("骷髅", "💀");
        emojiMap.put("嘘", "🤫");
        emojiMap.put("闭嘴", "🤐");
        emojiMap.put("傻眼", "😮");
        emojiMap.put("吃惊", "😲");
        emojiMap.put("吐", "🤮");
        emojiMap.put("感冒", "😷");
        emojiMap.put("生病", "🤒");
        emojiMap.put("拜拜", "👋");
        emojiMap.put("鄙视", "🖕");
        emojiMap.put("白眼", "🙄");
        emojiMap.put("抓狂", "😖");
        emojiMap.put("怒骂", "🤬");
        emojiMap.put("钱", "🤑");
        emojiMap.put("哈欠", "🥱");
        emojiMap.put("困", "😴");
        emojiMap.put("睡", "😪");
        emojiMap.put("吃瓜", "🍉");
        emojiMap.put("酸", "🍋");
        emojiMap.put("喵喵", "🐱");
        emojiMap.put("抱抱", "🤗");
        emojiMap.put("摊手", "🤷");
        emojiMap.put("跪了", "🧎");
        emojiMap.put("鲜花", "🌹");
        emojiMap.put("给你小心心", "💝");
        emojiMap.put("心", "❤");
        emojiMap.put("伤心", "💔");
        emojiMap.put("握手", "🤝");
        emojiMap.put("赞", "👍");
        emojiMap.put("good", "👍");
        emojiMap.put("弱", "👎");
        emojiMap.put("NO", "✋");
        emojiMap.put("耶", "✌");
        emojiMap.put("拳头", "✊");
        emojiMap.put("ok", "👌");
        emojiMap.put("加油", "💪");
        emojiMap.put("haha", "🤟");
        emojiMap.put("熊猫", "🐼");
        emojiMap.put("兔子", "🐰");
        emojiMap.put("猪头", "🐷");
        emojiMap.put("太阳", "🌞");
        emojiMap.put("月亮", "🌙");
        emojiMap.put("浮云", "☁");
        emojiMap.put("下雨", "🌧");
        emojiMap.put("微风", "🍃");
        emojiMap.put("围观", "👨‍👧‍👦");
        emojiMap.put("飞机", "✈");
        emojiMap.put("照相机", "📷");
        emojiMap.put("话筒", "🎙");
        emojiMap.put("蜡烛", "🕯");
        emojiMap.put("音乐", "🎵");
        emojiMap.put("可乐", "🥤");
        emojiMap.put("干杯", "🍻");
        emojiMap.put("蛋糕", "🎂");
        emojiMap.put("礼物", "🎁");
        emojiMap.put("钟", "⏰");
        emojiMap.put("肥皂", "🧼");
        emojiMap.put("绿丝带", "🎗");
        emojiMap.put("围脖", "🧣");
        emojiMap.put("圣诞老人", "🎅");
        emojiMap.put("文明遛狗", "🐕");
        emojiMap.put("棒棒糖", "🍭");
        emojiMap.put("看涨", "📈");
        emojiMap.put("全家福", "👪");
        emojiMap.put("最右", " →_→ ");
        emojiMap.put("炸鸡腿", "🍗");
        emojiMap.put("看跌", "📉");
        emojiMap.put("圆月", "🌕");
        emojiMap.put("五仁月饼", "🥮");
        emojiMap.put("点亮平安灯", "🏮");
        emojiMap.put("星星", "⭐");
        emojiMap.put("doge", "🐶");
        emojiMap.put("弗莱见钱眼开", "🤑");
        emojiMap.put("点亮橙色", "🖐");
        emojiMap.put("空星", "★");
        emojiMap.put("二哈", "🐶");
    }
}
