spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rssbot?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 112233
    driver-class-name: com.mysql.cj.jdbc.Driver


proxy:
  host: 127.0.0.1
  port: 7890

bot:
  token: 1254466910:AAGKH_ePhXkE9UzGQ19KHeC3q_6kLkU_dv0
  name: javaRSSBot

mybatis-plus:
  mapper-locations: classpath:tg/bot/rssgo/mapper/xml/*.xml
  type-aliases-package: tg.bot.rssgo.entity

logging:
  level:
    tg.bot.rssgo: debug
